ALTER TABLE "Drone" ADD COLUMN IF NOT EXISTS "droneId" TEXT;
ALTER TABLE "Drone" ADD COLUMN IF NOT EXISTS "altitude" DOUBLE PRECISION;
ALTER TABLE "Drone" ADD COLUMN IF NOT EXISTS "speed" DOUBLE PRECISION;
ALTER TABLE "Drone" ADD COLUMN IF NOT EXISTS "operatorLat" DOUBLE PRECISION;
ALTER TABLE "Drone" ADD COLUMN IF NOT EXISTS "operatorLon" DOUBLE PRECISION;
ALTER TABLE "Drone" ADD COLUMN IF NOT EXISTS "rssi" INTEGER;

CREATE INDEX IF NOT EXISTS "Drone_droneId_idx" ON "Drone"("droneId");
